//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteOfTheDay_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteList
    {
        public int ID { get; set; }
        public string Quote { get; set; }
        public string AuthorName { get; set; }
    }
}
